{% set version = "10.02.0" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}

package:
  name: ghostscript
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ version | replace(".", "") }}/ghostscript-{{ version }}.tar.gz
  sha256: e54062f166708d84ca82de9f8304a04344466080f936118b88082bd55ed6dc97

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - make       # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - gs --version
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}.{{ major }}  # [unix]
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}.{{ major }}.{{ minor }}  # [unix]

about:
  home: http://ghostscript.com/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: An interpreter for the PostScript language and for PDF

extra:
  recipe-maintainers:
    - seisman
    - ocefpaf
    - leouieda
    - tdegeus
