{% set version = "9.22" %}

package:
  name: ghostscript
  version: {{ version }}

source:
  fn: ghostscript-{{ version }}.tar.gz
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs922/ghostscript-{{ version }}.tar.gz
  sha256: 7f5f4487c0df9dce37481e4c8f192c0322e4c69f5a2ba900a7833c992331bcf4

build:
  number: 0

requirements:
  build:
    - gcc  # [not win]
    - posix  # [win]
    - m2w64-toolchain  # [win]

test:
  commands:
    - gs --version

about:
  home: http://ghostscript.com/
  license: Affero GPL
  license_file: LICENSE
  summary: 'An interpreter for the PostScript language and for PDF.'

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
