{% set version = "9.52" %}
{% set nopoint = "".join(version.split(".")) %}

package:
  name: ghostscript
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ nopoint }}/ghostscript-{{ version }}.tar.gz
  sha256: c2501d8e8e0814c4a5aa7e443e230e73d7af7f70287546f7b697e5ef49e32176
  patches:
    - dynlink_runtime.patch

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - gs --version

about:
  home: http://ghostscript.com/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: An interpreter for the PostScript language and for PDF

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
