{% set version = "10.05.1" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}

package:
  name: ghostscript
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ version | replace(".", "") }}/ghostscript-{{ version }}.tar.gz
  sha256: c0be073366d19471320dce13e210b4c47e14b01070d6cf3d2d6d6e8415344615

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - make       # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

test:
  commands:
    - gs --version
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}.{{ major }}  # [linux]
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}.{{ major }}.{{ minor }}  # [linux]
    - test -f ${PREFIX}/lib/libgs.{{ major }}${SHLIB_EXT}  # [osx]
    - test -f ${PREFIX}/lib/libgs.{{ major }}.{{ minor }}${SHLIB_EXT}  # [osx]    

about:
  home: http://ghostscript.com/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: An interpreter for the PostScript language and for PDF

extra:
  recipe-maintainers:
    - seisman
    - ocefpaf
    - leouieda
    - tdegeus
