appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OaeFlowJzntnpQ4J1hZm5TcBdktuBk29mdk5ijUfos2bDMf4cQXCu0TH6bZXcT3oYCVFjx4GcbCR5uU2dQQog1Qtheoj1buKG0qxYjhUY99i5/qd/a2e6z+F55eXuXRpO7N9x72oqZeb1JimTSx48+q12W4VidB/lsM3mcRLCXyBQoOn9ugMqbz7M2iV3yOw21nVAK7j1OWCmpzGsSY/diP+2E0LwNpQPuT2xSGD/WEF2OPncK0fN9zjUUEMOoROFbQULQyp4cbnIDdtlbzdDvDI2MpI7WgAxU6zKfDuht3LABft/jS8sTO1PshxgY2/qcqOzfzidXZR8f6AIrex73IrblDOFRXsY1aoUj1cNRennaFe3HBC6hMrF/lXNAj2nBbYhfV8g0IvexNPkfiKqHveNEpYl6USG8wJo1yngR040qGVQWec8xk6HE8yg4z1NMEff8zS5SBC9mKfskFMekEMYb/h/3fntG1VqjdTct/UNhgEug0sVUsWbcJ3HJ1kXMjApSa+H+ot78yFBiEIMoUsCZHCxSJZkKo48U68iYLsV/8riVOpMxoculTiGR/lcXpAW4HnZn3HL+byxb2OVeiEpaImoZwx4sKoEb0cN2ySjTpSI0RxoJ4g17eH8tV6ApQAcmwhxQj6Qe7XauPAtxYyRn+O88cPpBgg9wz1B80=}
provider:
  win: azure
